#!/bin/sh
#
# debug        debug
#

case "$1" in
  start)
	modprobe dwc_otg
	modprobe g_ether
	ifconfig usb0 up
	ifconfig usb0 172.3.0.2
	;;
  stop)
	;;
  restart|reload)
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

